# Generated by Django 4.2 on 2023-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=350)),
                ('password', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('Romania', '+40'), ('USA', '+1'), ('Germany', '+49'), ('France', '+33'), ('Italy', '+39'), ('Brazil', '+55')], max_length=100)),
                ('city', models.CharField(choices=[('Bucuresti', 'Bucurest'), ('Cluj-Napoca', 'Cluj'), ('Brasov', 'Brasov'), ('Constanta', 'Constanta'), ('Timisoara', 'Timisoara'), ('New York', 'New York'), ('Los Angeles', 'Los Angeles'), ('Chicago', 'Chicago'), ('Munich', 'Munich'), ('Berlin', 'Berlin'), ('Frankfurt', 'Frankfurt'), ('Paris', 'Paris'), ('Lyon', 'Lyon'), ('Roma', 'Roma'), ('Napoli', 'Napoli'), ('Sao Paulo', 'Sao Paulo'), ('Rio de Janeiro', 'Rio De Janeiro')], max_length=100)),
                ('role', models.CharField(choices=[('AGENT', 'Agent'), ('CUSTOMER', 'Customer')], max_length=50)),
            ],
        ),
    ]
