# Generated by Django 4.2 on 2023-04-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_propertyphoto_alter_user_table_property'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='property',
        ),
        migrations.AlterModelTable(
            name='propertyphoto',
            table='property_photo',
        ),
    ]
