# Generated by Django 4.2 on 2023-04-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_property_table_alter_propertyphoto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('Bucuresti', 'RO'), ('Cluj-NapocaRO', 'Cluj'), ('BrasovRO', 'Brasov'), ('ConstantaRO', 'Constanta'), ('TimisoaraRO', 'Timisoara'), ('New York', 'US'), ('Los Angeles', 'US'), ('Chicago', 'US'), ('Munich', 'GR'), ('Berlin', 'GR'), ('Frankfurt', 'GR'), ('Paris', 'FR'), ('Lyon', 'FR'), ('Roma', 'IT'), ('Napoli', 'IT'), ('Sao Paulo', 'BR'), ('Rio de Janeiro', 'BR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Bucuresti', 'RO'), ('Cluj-NapocaRO', 'Cluj'), ('BrasovRO', 'Brasov'), ('ConstantaRO', 'Constanta'), ('TimisoaraRO', 'Timisoara'), ('New York', 'US'), ('Los Angeles', 'US'), ('Chicago', 'US'), ('Munich', 'GR'), ('Berlin', 'GR'), ('Frankfurt', 'GR'), ('Paris', 'FR'), ('Lyon', 'FR'), ('Roma', 'IT'), ('Napoli', 'IT'), ('Sao Paulo', 'BR'), ('Rio de Janeiro', 'BR')], max_length=100),
        ),
    ]
