# Generated by Django 4.2 on 2023-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('Bucuresti', 'Romania'), ('Cluj-Napoca', 'Romania'), ('Brasov', 'Romania'), ('Constanta', 'Romania'), ('Timisoara', 'Romania'), ('New York', 'USA'), ('Los Angeles', 'USA'), ('Chicago', 'USA'), ('Munich', 'Germany'), ('Berlin', 'Germany'), ('Frankfurt', 'Germany'), ('Paris', 'France'), ('Lyon', 'France'), ('Roma', 'Italy'), ('Napoli', 'Italy'), ('Sao Paulo', 'Brazil'), ('Rio de Janeiro', 'Brazil')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(choices=[('Romania', 'Romania'), ('USA', 'Usa'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Brazil', 'Brazil')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Bucuresti', 'Romania'), ('Cluj-Napoca', 'Romania'), ('Brasov', 'Romania'), ('Constanta', 'Romania'), ('Timisoara', 'Romania'), ('New York', 'USA'), ('Los Angeles', 'USA'), ('Chicago', 'USA'), ('Munich', 'Germany'), ('Berlin', 'Germany'), ('Frankfurt', 'Germany'), ('Paris', 'France'), ('Lyon', 'France'), ('Roma', 'Italy'), ('Napoli', 'Italy'), ('Sao Paulo', 'Brazil'), ('Rio de Janeiro', 'Brazil')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('Romania', 'Romania'), ('USA', 'Usa'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Brazil', 'Brazil')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=350, unique=True),
        ),
    ]
