# Generated by Django 4.2 on 2023-04-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
