# Generated by Django 4.2 on 2023-04-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_property_photo_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='base.property'),
        ),
    ]
