# Generated by Django 4.2 on 2023-04-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyphoto',
            name='content',
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
