# Generated by Django 4.2 on 2023-04-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_propertyphoto_content_propertyphoto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
