# Generated by Django 4.2 on 2023-04-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_schedule'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
    ]
